NUM_CLASSES = 120

DATASET_NAME = 'stanford_dogs'

DATA_PATH = '/home/miafranc/zzz/xsvm/data'
DATA_FEATURES_PATH = 'data/'

DATA_PERCENTAGE = 1.0
VAL_SPLIT = 0.2

BATCH_SIZE = 32
NUM_EPOCHS = 100
PATIENCE = 20
OPTIMIZER = 'sgd'
LOSS = 'cross_entropy'
LOSS_HINGE_C = 1.0
LR = 1e-3
MOMENTUM = 0.9
WEIGHT_DECAY = 1e-4

NUM_EPOCHS_FINETUNE = 5
LR_FINETUNE = 1e-4

SCHEDULER = 'cosine'
STEP_SIZE = 10
STEP_GAMMA = 0.1
STEP_MULTI = [30, 60, 90]

MODEL_NAME = 'resnet50'
BASE_MODEL_BIAS = True
BEST_MODEL = 'acc'
MODEL_PATH = 'models/'
SAVE_BEST_MODEL = True
SAVE_MIN_ACC = 0.7

IMG_SIZE = 224

IMG_MEAN = [0.4761, 0.4518, 0.3910]
IMG_STD  = [0.2580, 0.2525, 0.2571]

TENSORBOARD_LOGDIR_PREFIX = 'runs/'

CUDA_ID = 0

CORRUPTION = None
CORRUPTION_BLUR_RADIUS = 2
CORRUPTION_NOISE_STD = 20
CORRUPTION_NOISE_BLEND = 30
CORRUPTION_CONTRAST = 1.5
CORRUPTION_BRIGHTNESS = 1.2
CORRUPTION_PIXELATE_LEVEL = 2
